name: 'PR-issue Sync Action'
#        when a PR is linked to an issue, issue status should change to "In review"
#        when a PR is linked to an issue, all of the issue's labels should be added to the PR
#        when a PR is not linked to an issue, it should be added to Project board with "In review" status
description: 'Syncs PRs with issues'
author: 'Code PushUp'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: node20
  main: dist/index.js
